dependencies:
  - name: service-account
    version: 0.5.0
    repository: https://ibm-garage-cloud.github.io/toolkit-charts/
  - name: service-account
    version: 0.5.0
    repository: https://ibm-garage-cloud.github.io/toolkit-charts/
    alias: config-service-account
  - name: artifactory
    version: 10.1.0
    repository: https://charts.jfrog.io/
  - name: ocp-route
    version: 0.3.0
    repository: https://ibm-garage-cloud.github.io/toolkit-charts/
  - name: tool-config
    version: 0.9.0
    repository: https://ibm-garage-cloud.github.io/toolkit-charts/
  - name: setup-job
    version: 0.1.5
    repository: https://ibm-garage-cloud.github.io/toolkit-charts/
